### ISSUE TITLE
Resumes page not working

### ISSUE THREAD

**Issue by victorantos** [victorantos/AngJobs#17]
The resumes page is not opening when browsing from here http://angjobs.com/#!/employer/applications

**Comment by PankajLala** [comment]
seems that 'cvs.service' is not being injected into the app as dependency and is throwing a $stateChangeError when the state is being changed to 'employer.resumes'
I would have preferred to submit a PR but facing challenges in setting up the app locally.

**Comment by victorantos** [comment]
Thanks!
Can you please submit a new issue regarding your challenges to setup the app locally,
I'll try to help you!

**Comment by PankajLala** [comment]
Thanks got it now, was facing issues with stripe.net and sql express setup.
