### ISSUE TITLE
"All jobs" menu link does not always work

### ISSUE THREAD

**Issue by victorantos** [victorantos/AngJobs#19]
Go to to HN jobs first 
http://angjobs.com/#!/jobs/inbox/hn

then select "All jobs" the page will still show HN jobs, only after you click on "Contract" and then again "All jobs" the link will display all jobs

**Comment by PankajLala** [comment]
Something wrong with changing state from location to jobtype inbox
from http://angjobs.com/#!/jobs/inbox/hn navigate to http://angjobs.com/#!/jobs/inbox view doesnt change ....add trailing '/' making url http://angjobs.com/#!/jobs/inbox/ voila view gets updated.
Tried making url:'' for abstract state 'jobs' and setting up $urlMatcherFactoryProvider.strictMode(false); but no success.
