### ISSUE TITLE
It's possible to load in linux/ubuntu?

### ISSUE THREAD

**Issue by mbenatti** [victorantos/AngJobs#40]
There's a way to load under linux?

**Comment by victorantos** [comment]
What do you mean? I'll give it a try in Ubuntu 15 later today

**Comment by mbenatti** [comment]
run the project under linux instead of windows.

**Comment by victorantos** [comment]
Ah, I see, you cannot run the project as it is under Linux

But I think you could use Mono to compile C#  - the server side code

It will still not work because it uses Sql Server, which does not run under Linux
