### ISSUE TITLE
 Mandrill is now an add-on for paid monthly MailChimp accounts, and is no longer available as a standalone service.

### ISSUE THREAD

**Issue by victorantos** [victorantos/AngJobs#44]
This will affect the email sending service from 27th of April

Find a replacement:
-  SendGrid?

**Comment by PankajLala** [comment]
Purely based on some  reseach my 2 cents are on SendinBlue or SendGrid
https://www.ventureharbour.com/transactional-email-service-best-mandrill-vs-sendgrid-vs-mailjet/

**Comment by victorantos** [comment]
Thanks! I think I'll choose SnedGrid because it has a free service for up to 12 000 emails per month

https://sendgrid.com/free
