### ISSUE TITLE
[Feature Request] run on Docker/Kubernetes

### ISSUE THREAD

**Issue by mightyhorst** [victorantos/AngJobs#59]
It would be awesome to see more dot net projects run on Docker out of the box to make it more widely compatible/homogenised with many CI/CD pipelines and running inside a Kubernetes cluster 

https://docs.docker.com/engine/examples/dotnetcore/

**Comment by mitni455** [comment]
Here you go. I'll create a pull request later on but here's the quick fix

Add this to the `Dockerfile` in the same file as the `.csproj`


```bash
FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app


########
# 
#  Install Node + Angular
# 
# 
RUN apt-get update -yq && apt-get upgrade -yq && apt-get install -yq build-essential libssl-dev nano nodejs

# npm 
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -

# node
RUN apt install nodejs

# check + set node 10 
RUN node --version
RUN npm -v


# angular 
RUN npm install -g @angular/cli yarn 


########
#
# Compile + Run 
#
# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "aspnetapp.dll"]

```

**Comment by victorantos** [comment]
Hi - really sorry not sure how I missed your comments...

**Comment by victorantos** [comment]
AngJobs has been changed recently quite a lot. To add  docker support, we might try this:

`#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY AngJobs.csproj ./
RUN dotnet restore "./AngJobs.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "AngJobs.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AngJobs.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AngJobs.dll"]
`
